apiVersion: v1
kind: Pod
metadata:
  name: kibana-pod
  labels:
    app: kibana-pod
spec:
  containers:
    - image: kibana:6.5.4
      name: kibana-pod
      imagePullPolicy: IfNotPresent
      env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
      ports:
        - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
    - name: 5601-5601
      port: 5601
      protocol: TCP
      targetPort: 5601
  type: ClusterIP
  selector:
    app: kibana-pod
